data:
  corpus_1:
    path_src: "data/trial2/train_inputs.txt"
    path_tgt: "data/trial2/train_targets.txt"
  valid:
    path_src: "data/trial2/valid_inputs.txt"
    path_tgt: "data/trial2/valid_targets.txt"

src_vocab: "data/trial2/vocabulary.txt"
tgt_vocab: "data/trial2/vocabulary.txt"

save_model: "models/trial2/tamil3"

train_steps: 500
valid_steps: 100
save_checkpoint_steps: 500
batch_size: 64
report_every: 100
