[project]
name = "linguisticfrankenstein"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jellyfish>=1.1.0",
    "numpy>=2.1.3",
    "opennmt-py>=3.5.1",
    "pandas>=2.2.3",
    "scikit-learn>=1.5.2",
]
