# config_tamil_data

# data
data:
  corpus_1:
    path_src: "data/train_inputs.txt"
    path_tgt: "data/train_targets.txt"
  valid:
    path_src: "data/valid_inputs.txt"
    path_tgt: "data/valid_targets.txt"

# save data
save_data: "data/processed_tamil"

# create src / tgt processed data
src_vocab: "data/processed_tamil.vocab.src"
tgt_vocab: "data/processed_tamil.vocab.tgt"
