data:
  corpus_1:
    path_src: "data/train_inputs_spm.txt"
    path_tgt: "data/train_targets_spm.txt"
  valid:
    path_src: "data/valid_inputs_spm.txt"
    path_tgt: "data/valid_targets_spm.txt"

src_vocab: "data/spm.vocab"
tgt_vocab: "data/spm.vocab"

save_model: "models/tamil2"

train_steps: 15000
valid_steps: 1000
save_checkpoint_steps: 1000
batch_size: 64
report_every: 100

world_size: 1
gpu_ranks: [0]
