data:
  corpus_1:
    path_src: "data/train_inputs_spm.txt"
    path_tgt: "data/train_targets_spm.txt"
  valid:
    path_src: "data/valid_inputs_spm.txt"
    path_tgt: "data/valid_targets_spm.txt"

src_vocab: "data/spm.vocab"
tgt_vocab: "data/spm.vocab"

save_model: "models/tamil3"

train_steps: 5000
valid_steps: 500
save_checkpoint_steps: 500
batch_size: 64
report_every: 100

world_size: 1

model_dtype: "fp32"

copy_attn: true
global_attention: "mlp"

src_subword_model: "..\\data\\spm.model"
tgt_subword_model: "..\\data\\spm.model"
src_subword_nbest: 1
tgt_subword_nbest: 1
src_subword_alpha: 0.0
tgt_subword_alpha: 0.0
src_subword_vocab_threshold: 0
tgt_subword_vocab_threshold: 0
