data:
  corpus_1:
    path_src: "data/train_inputs.txt"
    path_tgt: "data/train_targets.txt"
  valid:
    path_src: "data/valid_inputs.txt"
    path_tgt: "data/valid_targets.txt"

src_vocab: "data/vocabulary.txt"
tgt_vocab: "data/vocabulary.txt"

save_model: "models/tamil"

train_steps: 5000
valid_steps: 500
save_checkpoint_steps: 500
batch_size: 64
report_every: 100
